# 기본 학습 설정
model:
  detector: 'yolov10x'
  yolo_ft: 'None'
  # yolo_ft: 'taa/model/weights/DAD/yolov10x_epoch_15.pt'
  conf_thresh: 0.10
  opticalflow: 'None'
  # opticalflow: 'neuflow'

train:
  num_epochs: 100
  batch_size: 2  # GPU당 배치 크기
  num_workers: 2
  optimizer: 'SGD'
  learning_rate: 5e-2
  scheduler: 'ReduceLROnPlateau'
  resume: False  # Whether to resume from checkpoint
  resume_path: 'taa/_experiments/20250129_080203/checkpoints/best_model.pth'  # Path to checkpoint file

loss:
  name: 'AdaLEA' # 'TAATemporal' or 'AdaLEA'
  lambda_temporal: 0.
  lambda_attn: 10  # Added attention loss weight
  iou_thresh: 0.5   # Added IoU threshold for attention loss
  gamma: 5.0 # for AdaLEA

# 데이터셋 설정
dataset:
  name: 'DAD'
  root_path: './taa/data/DAD'
  hdf5: False
  img_size: [640, 640]
  fps: 20.0
  toa: 90

# DDP 설정
distributed:
  enabled: true
  world_size: 4
  gpu_ids: [0, 1, 2, 3]
  backend: 'nccl'
  master_addr: 'localhost'
  master_port: '12355'

# 로깅 설정
logging:
  log_interval: 100  # steps
  save_interval: 1   # epochs